app:
  version: 1
  name: short-app
  replicas: 1
  components: frontend 
  image: antonlarichev/short-app
  tag: v1.4
  port: 80
  limits: 
    memory: "128Mi"
    cpu: "100m"

env: test
value:
  requirements:
    limits:
      memory: "128Mi"
      cpu: "100m"


users:
  - name: Nick
    role: admin
  - name: Anton
    role: user