apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include "chart.labels" . | indent 4 }}
data:
  name: {{ .Values.app.version | quote }}
  {{- if eq .Values.env "production" }}
  paymentToken: "1234"
  {{- else }}
  paymentToken: false
  {{- end }}
  {{- with .Values.value.requirements.limits }}
  memory: {{ .memory }}
  cpu: {{ .cpu }}
  version: {{ $.Release.name }}
  {{- end }}
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
  users:
    {{- range $index, $user := .Values.users }}
    - {{ $user.name }}: "{{ $user.role }} - {{ $index }}"
    {{- end }}
  users_tuple:
    {{- range tuple "Nick" "Anton" }}
    - {{ . }}
    {{- end }}